name = "sodapop"
main = "_worker.js"
compatibility_date = "2024-10-01"

[[durable_objects.bindings]]
name = "ROOM_DO"
class_name = "RoomDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]

[site]
bucket = "./"
