name = "soda-pop-bubbles"
main = "_worker.js"
compatibility_date = "2024-10-01"

[[durable_objects.bindings]]
name = "ROOM_DO"
class_name = "RoomDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["RoomDurableObject"]

[site]              # only for Workers Sites; for Cloudflare Pages, omit [site]
bucket = "./"       # serve index.html etc. (if using Workers Sites)

[assets]            # for Cloudflare Pages Functions-in-Pages
binding = "ASSETS"
